"""Generate a fresh LiveKit room name and participant token for local testing."""

from __future__ import annotations

import argparse
import json
import secrets
from datetime import UTC, datetime, timedelta
from pathlib import Path

from livekit.api import AccessToken, VideoGrants

from taigi_flow.bootstrap import load_env_file
from taigi_flow.config import Settings

load_env_file(Path(__file__).resolve().parents[3] / ".env.local")


def generate_room_name(prefix: str = "test-room") -> str:
    timestamp = datetime.now(UTC).strftime("%Y%m%d-%H%M%S")
    suffix = secrets.token_hex(3)
    return f"{prefix}-{timestamp}-{suffix}"


def create_participant_token(
    *,
    api_key: str,
    api_secret: str,
    room: str,
    identity: str,
    ttl_minutes: int,
    name: str | None = None,
) -> str:
    token = (
        AccessToken(api_key=api_key, api_secret=api_secret)
        .with_identity(identity)
        .with_name(name or identity)
        .with_ttl(timedelta(minutes=ttl_minutes))
        .with_grants(
            VideoGrants(
                room_join=True,
                room=room,
                can_publish=True,
                can_subscribe=True,
                can_publish_data=True,
            )
        )
    )
    return token.to_jwt()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate a fresh LiveKit room name and participant token."
    )
    parser.add_argument("--room", help="Reuse a specific room name instead of generating one.")
    parser.add_argument(
        "--room-prefix",
        default="test-room",
        help="Prefix for autogenerated room names. Default: test-room",
    )
    parser.add_argument(
        "--identity",
        default="user1",
        help="Participant identity embedded in the token. Default: user1",
    )
    parser.add_argument(
        "--name",
        help="Participant display name. Defaults to the identity.",
    )
    parser.add_argument(
        "--ttl-minutes",
        type=int,
        default=60,
        help="Token lifetime in minutes. Default: 60",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print machine-readable JSON instead of plain text.",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    settings = Settings()
    room = args.room or generate_room_name(args.room_prefix)

    token = create_participant_token(
        api_key=settings.livekit_api_key,
        api_secret=settings.livekit_api_secret,
        room=room,
        identity=args.identity,
        ttl_minutes=args.ttl_minutes,
        name=args.name,
    )

    payload = {
        "livekit_url": settings.livekit_url,
        "room": room,
        "identity": args.identity,
        "name": args.name or args.identity,
        "ttl_minutes": args.ttl_minutes,
        "token": token,
    }

    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return

    print(f"LIVEKIT_URL={payload['livekit_url']}")
    print(f"ROOM={payload['room']}")
    print(f"IDENTITY={payload['identity']}")
    print(f"NAME={payload['name']}")
    print(f"TTL_MINUTES={payload['ttl_minutes']}")
    print(f"TOKEN={payload['token']}")


if __name__ == "__main__":
    main()
